name: example
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_parts:
    path: ..
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^7.6.7
  the_utils: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svgs/
    - assets/images/
  fonts:
   - family: scale
     fonts:
      - asset: assets/fonts/scale.ttf
