name: flutter_parts
description: A practical UI component library that integrates multiple widgets commonly used in Flutter projects, aimed at helping developers build comprehensive UI effects within the shortest possible time frame.

version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

auth:
  name: Jcak Lee
  email: 291148484@163.com
  home: http://thispage.tech
maintainer: Jcak Lee
repository: https://github.com/jacklee1995/flutter_parts
issue_tracker: https://github.com/jacklee1995/flutter_parts/issues

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
